package nonetheless.prayertime.model

enum class City(val id: Int, val text: String) {
    Rabat(1,"Rabat"),
    Khémissat(2,"Khémissat"),
    Tiflet(3,"Tiflet"),
    Remani(4,"Remani"),
    Oualmas(5,"Oualmas"),
    Bouznika(6,"Bouznika"),
    Kénitra(7,"Kénitra"),
    Sidi_Kacem(8,"Sidi Kacem"),
    Sidi_yahya_lgharb(9,"Sidi yahya lgharb"),
    Sidi_Slimane(10,"Sidi Slimane"),
    Souk_arbiaa_lgharb(11,"Souk arbiaa lgharb"),
    Arbaoua(12,"Arbaoua"),
    Mmoulay_Bouselham(13,"Mmoulay Bouselham"),
    Tanger(14,"Tanger"),
    Tetouan(15,"Tetouan"),
    Araich(16,"Araich"),
    Assila(17,"Assila"),
    Chefchaoun(18,"Chefchaoun"),
    Martil(19,"Martil"),
    MDiq(20,"M'Diq"),
    Laksar_Lakbire(21,"Laksar Lakbire"),
    Laksar_Sghir(22,"Laksar Sghir"),
    Alhoceima(23,"Alhoceima"),
    Sebta(24,"Sebta"),
    Fnideq(25,"Fnideq"),
    Jebha(26,"Jebha"),
    Oued_laou(27,"Oued laou"),
    Bab_berred(28,"Bab berred"),
    Ouazzan(29,"Ouazzan"),
    Bouskoura(30,"Bouskoura"),
    Oujda(31,"Oujda"),
    Berkane(32,"Berkane"),
    Feguig(33,"Feguig"),
    Bouâarfa(34,"Bouâarfa"),
    Guersif(35,"Guersif"),
    Jrada(36,"Jrada"),
    Ain_châir(37,"Ain châir"),
    Taourirt(38,"Taourirt"),
    Nador(39,"Nador"),
    Melilla(40,"Melilla"),
    Debdou(41,"Debdou"),
    Selouane(42,"Selouane"),
    Beni_Ensar(43,"Beni Ensar"),
    Ferkhana(44,"Ferkhana"),
    Talsinet(45,"Talsinet"),
    Tindrara(46,"Tindrara"),
    El_Aïoun_Charqiya(47,"El Aïoun Charqiya"),
    Bni_Drar(48,"Bni Drar"),
    Saïdia(49,"Saïdia"),
    Ras_Lma(50,"Ras Lma"),
    Tafoughalt(51,"Tafoughalt"),
    Fezouane(52,"Fezouane"),
    Ahfir(53,"Ahfir"),
    Zaio(54,"Zaio"),
    Driouech(55,"Driouech"),
    Beni_Tejit(56,"Beni Tejit"),
    Bouanane(57,"Bouanane"),
    Casablanca(58,"Casablanca"),
    Mohammadia(59,"Mohammadia"),
    Benslimane(60,"Benslimane"),
    Settat(61,"Settat"),
    Lgara(62,"Lgara"),
    El_Borouj(63,"El Borouj"),
    Beni_Ahmed(64,"Beni Ahmed"),
    Berrchid(65,"Berrchid"),
    Eljadida(66,"Eljadida"),
    Azemour(67,"Azemour"),
    Sidi_Bennour(68,"Sidi Bennour"),
    Zemamra(69,"Zemamra"),
    Khénifra(70,"Khénifra"),
    Moulay_Bouâaza(71,"Moulay Bouâaza"),
    Zaouiat_Ahensal(72,"Zaouiat Ahensal"),
    Beni_Mellal(73,"Beni Mellal"),
    Azilal(74,"Azilal"),
    Fquih_Ben_Salah(75,"Fquih Ben Salah"),
    Demnat(76,"Demnat"),
    El_Ksiba(77,"El Ksiba"),
    Kasba_Tadla(78,"Kasba Tadla"),
    Khouribga(79,"Khouribga"),
    Oued_Zem(80,"Oued Zem"),
    Fes(81,"Fes"),
    Sefrou(82,"Sefrou"),
    Moulay_Yaâgoub(83,"Moulay Yaâgoub"),
    Boulmane(84,"Boulmane"),
    Missour(85,"Missour"),
    Ribate_El_Kheïr(86,"Ribate El Kheïr"),
    El_Menzel(87,"El Menzel"),
    Imouzar_Kandar(88,"Imouzar Kandar"),
    Taza(89,"Taza"),
    Taounat(90,"Taounat"),
    Aknoul(91,"Aknoul"),
    Tizi_ousli(92,"Tizi ousli"),
    Bourd(93,"Bourd"),
    Tahla(94,"Tahla"),
    Tissa(95,"Tissa"),
    Karia_Ba_Mohamed(96,"Karia Ba Mohamed"),
    Ketama(97,"Ketama"),
    Oued_Amlil(98,"Oued Amlil"),
    Meknes(99,"Meknes"),
    Ifrane(100,"Ifrane"),
    El_Hajeb(101,"El Hajeb"),
    Zerhoun(102,"Zerhoun"),
    Azrou(103,"Azrou"),
    Merrakech(104,"Merrakech"),
    Kelâat_Esraghna(105,"Kelâat Esraghna"),
    Essaouira(106,"Essaouira"),
    Chichaoua(107,"Chichaoua"),
    Bengrire(108,"Bengrire"),
    Rehamna(109,"Rehamna"),
    Tamanar(110,"Tamanar"),
    Safi(111,"Safi"),
    Oualidia(112,"Oualidia"),
    Youssoufia(113,"Youssoufia"),
    Tassoultante(114,"Tassoultante"),
    Tamesluht(115,"Tamesluht"),
    Kettara(116,"Kettara"),
    Agadir(117,"Agadir"),
    Taroudant(118,"Taroudant"),
    Tiznit(119,"Tiznit"),
    Irherm(120,"Irherm"),
    Taliouine(121,"Taliouine"),
    Tafraoute(122,"Tafraoute"),
    Tata(123,"Tata"),
    Akka(124,"Akka"),
    Fam_El_Hisn(125,"Fam El Hisn"),
    Biougra(126,"Biougra"),
    Oulad_Teima(127,"Oulad Teima"),
    Errachidia(128,"Errachidia"),
    Rissani(129,"Rissani"),
    Arfoud(130,"Arfoud"),
    Tandit(131,"Tandit"),
    Goulmima(132,"Goulmima"),
    Imilchil(133,"Imilchil"),
    Tinejdad(134,"Tinejdad"),
    Er_Rich(135,"Er-Rich"),
    Midelt(136,"Midelt"),
    Zagora(137,"Zagora"),
    Ouarzazate(138,"Ouarzazate"),
    Tinghir(139,"Tinghir"),
    Haskora(140,"Haskora"),
    Kalaat_MGouna(141,"Kalaat M'Gouna"),
    Agdz(142,"Agdz"),
    Boumalne_Dades(143,"Boumalne Dades"),
    Alnif(144,"Alnif"),
    Assoul(145,"Assoul"),
    Msemrir(146,"Msemrir"),
    Tazarine(147,"Tazarine"),
    Sidi_Ifni(148,"Sidi Ifni"),
    Guelmim(149,"Guelmim"),
    Assa(150,"Assa"),
    Zag(151,"Zag"),
    Tantan(152,"Tantan"),
    Bouizakarne(153,"Bouizakarne"),
    Al_Mahbes(154,"Al Mahbes"),
    Lamsid(155,"Lamsid"),
    Laayoune(156,"Laayoune"),
    Samara(157,"Samara"),
    Boujdour(158,"Boujdour"),
    Tarfaia(159,"Tarfaia"),
    Tifariti(160,"Tifariti"),
    Bu_Craa(161,"Bu Craa"),
    Guelta_Zemmur(162,"Guelta Zemmur"),
    Amgala(163,"Amgala"),
    Akhfennir(164,"Akhfennir"),
    Dakhla(165,"Dakhla"),
    Lagouira(166,"Lagouira"),
    Awsard(167,"Awsard"),
    Bir_Gandus(168,"Bir Gandus"),
    Bir_Anzerane(169,"Bir Anzerane"),
    Khmiss_Sidi_Abdeljalil(301,"Khmiss Sidi Abdeljalil"),
    Oulad_Ayad(302,"Oulad Ayad"),
    Matmata(304,"Matmata"),
    Imintanoute(305,"Imintanoute"),
    Sidi_Ghanem(306,"Sidi Ghanem"),
    Tifntan(307,"Tifntan"),
    Ait_Aque(308,"Ait Aque"),
    Agdal_Imilchil(309,"Agdal Imilchil"),
    Agoudal(310,"Agoudal"),
    Akaywar(311,"Akaywar"),
    Aïn_El_Aouda(312,"Aïn El Aouda"),
    Asguin(313,"Asguin"),
    Ait_Ourir(314,"Ait Ourir"),
    Zaouyat_My_Brahim(315,"Zaouyat My Brahim"),
    Toulkoult(316,"Toulkoult"),
    Iguisse(317,"Iguisse"),
    Kors(318,"Kors"),
    Tissint(319,"Tissint"),
    Foum_Zguid(320,"Foum Zguid"),
    Ksar_Ich(321,"Ksar Ich"),
}